# Generated by Django 4.0.5 on 2022-06-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.IntegerField(verbose_name=((0, 'NEW'), (1, 'PROCCESS'), (2, 'COMPLETED'))),
        ),
    ]
